version: '3.8'

services:
  web:
    image: "node:20"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
    entrypoint: ["/bin/sh", "/app/entrypoint.sh"]